// Module included in the following assemblies:
//
// * virt/live_migration/virt-live-migration.adoc

[id="virt-understanding-live-migration_{context}"]
= Understanding live migration

Live migration is the process of moving a running virtual machine instance (VMI) to
another node in the cluster without interrupting the virtual workload or access.
If a VMI uses the `LiveMigrate` eviction strategy, it automatically migrates
when the node that the VMI runs on is placed into maintenance mode. You can also
manually start live migration by selecting a VMI to migrate.

.Limitations

- Virtual machines must have a persistent volume claim (PVC) with a shared
ReadWriteMany (RWX) access mode to be live migrated.

- Live migration is not allowed with a pod network binding of bridge interface type ()

- Live migration requires ports 49152, 49153 to be available in the virt-launcher pod. If these ports are explicitly specified in masquarade interface, live migration will not function.

- Live migration is supported for virtual machines that are attached to an SR-IOV network interface only if the `sriovLiveMigration` feature gate is enabled in the HyperConverged Cluster custom resource (CR). When the `spec.featureGates.sriovLiveMigration` field is set to `true`, the `virt-launcher` pod runs with the `SYS_RESOURCE` capability. This might degrade its security.

